import React, { useState, useEffect, useRef, useLayoutEffect } from 'react';
import { Property, ViewState, SiteSettings } from './types';
import { generatePropertyDescription } from './services/geminiService';
import { supabase, updateSupabaseCredentials, resetSupabaseCredentials } from './services/supabaseClient';
import { PropertyCard } from './components/PropertyCard';
import { 
  LayoutDashboard, Plus, Settings, Phone, Palette, Save, Trash2, 
  Image as ImageIcon, Edit, UserCircle, Globe,
  ArrowLeft, X, Camera, Sparkles, MapPin, Bed, Bath, Expand, CheckCircle,
  AlertTriangle, RefreshCw, ChevronLeft, ChevronRight, Upload,
  Eye, EyeOff, Star, FileText, Facebook, Instagram, Mail, Clock, Filter, Calendar, DollarSign, Lock, LogIn, Users, Key, ShieldCheck, HardDrive, Database
} from 'lucide-react';

// --- ERROR BOUNDARY ---
interface ErrorBoundaryProps { children?: React.ReactNode; }
interface ErrorBoundaryState { hasError: boolean; error: Error | null; }

class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  state: ErrorBoundaryState = { hasError: false, error: null };

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  render() {
    if (this.state.hasError) {
      const loader = document.getElementById('loading-screen');
      if (loader) loader.style.display = 'none';

      return (
        <div className="min-h-screen flex items-center justify-center bg-red-50 p-4 text-center">
          <div className="bg-white p-8 rounded-xl shadow-lg max-w-lg">
            <AlertTriangle size={48} className="mx-auto text-red-600 mb-4" />
            <h1 className="text-xl font-bold text-red-700 mb-2">Erro de Renderização</h1>
            <p className="text-gray-600 mb-4">Ocorreu um erro ao exibir a interface.</p>
            <pre className="bg-gray-100 p-2 rounded text-xs text-left overflow-auto mb-4 max-h-40">
              {this.state.error?.message}
            </pre>
            <button onClick={() => window.location.reload()} className="bg-red-600 text-white px-4 py-2 rounded">Recarregar</button>
          </div>
        </div>
      );
    }
    return (this as any).props.children;
  }
}

// --- UTILS ---
const maskPhone = (value: string) => value.replace(/\D/g, '').replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2').replace(/(-\d{4})\d+?$/, '$1');

// Upload real para Supabase Storage
const uploadImage = async (file: File): Promise<string | null> => {
  try {
    const fileExt = file.name.split('.').pop();
    const cleanName = file.name.replace(/[^a-zA-Z0-9]/g, '');
    const fileName = `${Date.now()}_${cleanName}.${fileExt}`;
    
    console.log("Iniciando upload para:", fileName);

    const { data, error: uploadError } = await supabase.storage
      .from('images')
      .upload(fileName, file, {
        cacheControl: '3600',
        upsert: false
      });

    if (uploadError) {
      console.error("Erro detalhado do upload:", uploadError);
      throw uploadError;
    }

    const { data: urlData } = supabase.storage.from('images').getPublicUrl(fileName);
    
    if (!urlData || !urlData.publicUrl) {
      throw new Error("Não foi possível gerar a URL pública.");
    }

    console.log("Upload Sucesso:", urlData.publicUrl);
    return urlData.publicUrl;

  } catch (error: any) {
    console.error("FALHA NO UPLOAD:", error);
    
    let msg = error.message || "Erro desconhecido";
    
    if (msg.includes('row-level security') || msg.includes('new row violates')) {
      alert('ERRO DE PERMISSÃO: O Supabase bloqueou o envio.\n\nSOLUÇÃO: Vá em Configurações > Ajuda DB e rode o SQL.');
    } else if (msg.includes('Bucket not found')) {
      alert('ERRO: O Bucket "images" não existe.\n\nSOLUÇÃO: Rode o SQL de atualização no Supabase.');
    } else {
      alert('Erro no upload: ' + msg);
    }
    return null;
  }
};

// --- SQL SETUP (ATUALIZADO COM MAX_GUESTS) ---
const SQL_SETUP_CODE = `-- 1. TABELAS (Estrutura)
create table if not exists properties (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  location text,
  price numeric,
  type text, 
  bedrooms integer,
  bathrooms integer,
  area numeric,
  features text[],
  images text[],
  views integer default 0,
  active boolean default true,
  featured boolean default false,
  owner_notes text,
  max_guests integer default 0
);

create table if not exists site_settings (
  id int primary key generated by default as identity,
  data jsonb not null
);
insert into site_settings (id, data) values (1, '{}'::jsonb) on conflict (id) do nothing;

-- 2. MIGRAÇÃO DE COLUNAS
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='active') then
    alter table properties add column active boolean default true;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='featured') then
    alter table properties add column featured boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='owner_notes') then
    alter table properties add column owner_notes text;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='max_guests') then
    alter table properties add column max_guests integer default 0;
  end if;
end
$$;

-- 3. PERMISSÕES DE TABELAS
alter table properties enable row level security;
alter table site_settings enable row level security;

drop policy if exists "Public Access" on properties;
drop policy if exists "Public Settings" on site_settings;

create policy "Public Access" on properties for all using (true) with check (true);
create policy "Public Settings" on site_settings for all using (true) with check (true);

-- 4. STORAGE (IMAGENS)
insert into storage.buckets (id, name, public) 
values ('images', 'images', true) 
on conflict (id) do update set public = true;

grant all on schema storage to postgres, anon, authenticated, service_role;
grant all on table storage.objects to postgres, anon, authenticated, service_role;

drop policy if exists "Public Views" on storage.objects;
drop policy if exists "Public Uploads" on storage.objects;
drop policy if exists "Public Deletes" on storage.objects;
drop policy if exists "Anon Insert" on storage.objects;
drop policy if exists "Anon Select" on storage.objects;
drop policy if exists "Anon Delete" on storage.objects;

create policy "Anon Insert" on storage.objects for insert with check ( bucket_id = 'images' );
create policy "Anon Select" on storage.objects for select using ( bucket_id = 'images' );
create policy "Anon Delete" on storage.objects for delete using ( bucket_id = 'images' );
`;

const UbatubaLogo: React.FC<{ className?: string }> = ({ className }) => (
  <svg viewBox="0 0 200 200" className={className} fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="100" cy="100" r="95" stroke="currentColor" strokeWidth="8" className="text-ocean-600" fill="white"/>
    <path d="M30 90 L100 40 L170 90" stroke="currentColor" strokeWidth="8" strokeLinecap="round" className="text-ocean-800"/>
    <path d="M55 72 L55 55 L65 55 L65 65" stroke="currentColor" strokeWidth="6" className="text-ocean-800"/>
    <rect x="60" y="90" width="20" height="20" fill="currentColor" className="text-ocean-800"/>
    <rect x="120" y="90" width="20" height="20" fill="currentColor" className="text-ocean-800"/>
    <text x="100" y="135" textAnchor="middle" fontFamily="Arial, sans-serif" fontWeight="900" fontSize="28" fill="black" letterSpacing="-1">ALUGA-SE</text>
    <text x="100" y="160" textAnchor="middle" fontFamily="Arial, sans-serif" fontWeight="900" fontSize="28" className="fill-ocean-600" letterSpacing="-1">UBATUBA</text>
    <text x="160" y="175" textAnchor="end" fontFamily="Arial, sans-serif" fontWeight="bold" fontSize="12" className="fill-ocean-600">.COM</text>
    <path d="M20 115 Q 50 105, 80 115 T 140 115 T 180 105" stroke="currentColor" strokeWidth="4" fill="none" className="text-ocean-400"/>
  </svg>
);

const LoadingSpinner: React.FC = () => (
  <div className="flex flex-col items-center justify-center min-h-[50vh] w-full animate-in fade-in">
    <div className="relative mb-4">
      <div className="w-16 h-16 border-4 border-ocean-100 border-t-ocean-600 rounded-full animate-spin"></div>
      <div className="absolute inset-0 flex items-center justify-center">
        <UbatubaLogo className="w-6 h-6 text-ocean-600 opacity-50" />
      </div>
    </div>
    <p className="text-ocean-600 font-bold animate-pulse text-sm uppercase tracking-widest">Carregando...</p>
  </div>
);

const INITIAL_SETTINGS: SiteSettings = {
  siteName: 'Aluga-se Ubatuba',
  logoUrl: '/img/LOGO_LEGAL.png', 
  primaryColor: 'ocean',
  contact: {
    address: 'Av. Leovigildo Dias Vieira, 1000 - Itaguá',
    phone: '(12) 99999-9999',
    bookingPhone: '(12) 98888-8888', 
    email: 'contato@alugaseubatuba.com.br',
    hours: 'Seg a Sex: 09h - 18h | Sáb: 09h - 13h'
  },
  social: { instagram: '@alugaseubatuba', facebook: '/alugaseubatuba' }
};

// --- COMPONENTES ---

const Footer: React.FC<{ settings: SiteSettings }> = ({ settings }) => {
  const [imgError, setImgError] = useState(false);

  useEffect(() => { setImgError(false); }, [settings.logoUrl]);

  const getSocialLink = (value: string, baseUrl: string) => {
    if (!value) return '#';
    if (value.startsWith('http')) return value;
    const clean = value.replace(/^@|^\//, '');
    return `${baseUrl}/${clean}`;
  };

  return (
    <footer className="bg-ocean-900 text-ocean-50 pt-12 pb-6 mt-12 transition-colors duration-300">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          <div>
            <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
              <div className="bg-white rounded-full p-1 h-10 w-10 flex items-center justify-center overflow-hidden">
                {settings.logoUrl && !imgError ? (
                  <img src={settings.logoUrl} className="h-full w-full object-contain" alt="Logo Footer" onError={() => setImgError(true)} />
                ) : (
                  <UbatubaLogo className="h-8 w-8 text-ocean-600"/>
                )}
              </div>
              {settings.siteName}
            </h3>
            <p className="text-ocean-200 text-sm leading-relaxed">
              Encontre o seu imóvel ideal no litoral. Venda e Aluguel de Temporada com total segurança.
            </p>
          </div>
          <div>
            <h4 className="font-bold text-lg mb-4 text-ocean-300">Contato</h4>
            <ul className="space-y-3 text-sm text-ocean-100">
              <li className="flex items-start gap-3"><MapPin size={18} className="mt-0.5 text-ocean-400"/> {settings.contact.address}</li>
              <li className="flex items-center gap-3"><Phone size={18} className="text-ocean-400"/> {settings.contact.phone}</li>
              <li className="flex items-center gap-3"><Mail size={18} className="text-ocean-400"/> {settings.contact.email}</li>
              <li className="flex items-center gap-3"><Clock size={18} className="text-ocean-400"/> {settings.contact.hours}</li>
            </ul>
          </div>
          <div>
            <h4 className="font-bold text-lg mb-4 text-ocean-300">Redes Sociais</h4>
            <div className="flex gap-4">
              <a href={getSocialLink(settings.social.instagram, 'https://instagram.com')} target="_blank" rel="noopener noreferrer" className="bg-ocean-800 p-3 rounded-full hover:bg-ocean-600 text-white transition-colors"><Instagram size={20}/></a>
              <a href={getSocialLink(settings.social.facebook, 'https://facebook.com')} target="_blank" rel="noopener noreferrer" className="bg-ocean-800 p-3 rounded-full hover:bg-ocean-600 text-white transition-colors"><Facebook size={20}/></a>
            </div>
            <div className="mt-6">
               <button onClick={() => window.open(`https://wa.me/${(settings.contact.bookingPhone || settings.contact.phone).replace(/\D/g, '')}`, '_blank')} className="bg-green-600 hover:bg-green-700 text-white py-2 px-6 rounded-full font-bold w-full md:w-auto flex items-center justify-center gap-2 shadow-lg transform hover:scale-105 transition-all">
                 <Phone size={18}/> WhatsApp
               </button>
            </div>
          </div>
        </div>
        <div className="border-t border-ocean-800 pt-6 text-center text-sm text-ocean-300">
          &copy; {new Date().getFullYear()} {settings.siteName}. Todos os direitos reservados.
        </div>
      </div>
    </footer>
  );
};

const AdminLoginModal: React.FC<{ isOpen: boolean; onClose: () => void; onLogin: () => void }> = ({ isOpen, onClose, onLogin }) => {
  const [password, setPassword] = useState('');
  const [error, setError] = useState(false);

  if (!isOpen) return null;
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (password === 'fechadura') {
      onLogin();
      setPassword('');
      setError(false);
    } else {
      setError(true);
    }
  };
  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
      <div className="bg-white rounded-2xl shadow-2xl p-8 max-w-sm w-full relative animate-in fade-in zoom-in duration-200">
        <button onClick={onClose} className="absolute top-4 right-4 text-gray-400 hover:text-gray-600"><X size={24}/></button>
        <div className="flex flex-col items-center mb-6">
          <div className="bg-ocean-100 p-4 rounded-full mb-4 text-ocean-600"><Lock size={32}/></div>
          <h2 className="text-2xl font-bold text-ocean-800">Área Restrita</h2>
          <p className="text-sm text-gray-500 text-center">Digite a senha de administrador.</p>
        </div>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
             <input type="password" className={`w-full p-3 border rounded-lg text-center font-bold tracking-widest text-lg outline-none focus:ring-2 ${error ? 'border-red-300 focus:ring-red-200 bg-red-50' : 'border-ocean-200 focus:ring-ocean-200'}`} placeholder="Senha" value={password} onChange={e => { setPassword(e.target.value); setError(false); }} autoFocus />
             {error && <p className="text-red-500 text-xs text-center mt-2 font-bold">Senha incorreta.</p>}
          </div>
          <button type="submit" className="w-full bg-ocean-600 hover:bg-ocean-700 text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2 shadow-lg"><LogIn size={20}/> Entrar</button>
        </form>
      </div>
    </div>
  );
};

const DatabaseSetup: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const [url, setUrl] = useState(localStorage.getItem('sb_url') || '');
  const [key, setKey] = useState(localStorage.getItem('sb_key') || '');
  const [checking, setChecking] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(SQL_SETUP_CODE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleConnect = () => {
    if(!url || !key) return alert("Preencha URL e Chave!");
    updateSupabaseCredentials(url, key);
  };

  const handleVerify = async () => {
    setChecking(true);
    try {
      const { error } = await supabase.from('properties').select('id').limit(1);
      if (error && error.code === '42P01') {
        alert("❌ As tabelas ainda não foram encontradas.\n\nPor favor, copie o SQL acima e rode no Supabase.");
      } else {
        alert("✅ Conectado com sucesso!\nO sistema será recarregado.");
        window.location.reload();
      }
    } catch (e) {
      alert("Erro ao verificar: " + e);
    }
    setChecking(false);
  };

  return (
    <div className="container mx-auto px-4 py-12 flex flex-col items-center justify-center min-h-[80vh] text-center max-w-4xl">
      <div className="bg-ocean-50 text-ocean-600 p-6 rounded-full mb-6 shadow-xl animate-bounce"><HardDrive size={64} /></div>
      <h1 className="text-3xl md:text-4xl font-bold text-main mb-2">Instalador do Sistema</h1>
      <p className="text-muted max-w-2xl mb-8 text-lg">
        Configure o banco de dados para iniciar o aplicativo.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 w-full text-left">
        {/* PASSO 1: CONEXÃO */}
        <div className="bg-white border border-ocean-100 rounded-xl shadow-lg p-6">
           <h3 className="font-bold text-ocean-800 mb-4 border-b pb-2 flex items-center gap-2"><div className="bg-ocean-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-xs">1</div> Conexão com Supabase</h3>
           <p className="text-sm text-gray-500 mb-4">Insira as credenciais do NOVO projeto criado no Supabase.</p>
           <div className="space-y-3">
             <div>
               <label className="block text-xs font-bold text-gray-500 mb-1">Project URL</label>
               <input className="w-full p-2 border rounded text-sm bg-gray-50" value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://xxx.supabase.co" />
             </div>
             <div>
               <label className="block text-xs font-bold text-gray-500 mb-1">Anon Key (Public)</label>
               <input className="w-full p-2 border rounded text-sm bg-gray-50" value={key} onChange={e=>setKey(e.target.value)} placeholder="eyJh..." />
             </div>
             <button onClick={handleConnect} className="w-full bg-ocean-600 text-white py-2 rounded font-bold hover:bg-ocean-700 mt-2">Salvar Credenciais</button>
           </div>
        </div>

        {/* PASSO 2: ESTRUTURA */}
        <div className="bg-white border border-ocean-100 rounded-xl shadow-lg p-6 flex flex-col">
           <h3 className="font-bold text-ocean-800 mb-4 border-b pb-2 flex items-center gap-2"><div className="bg-ocean-600 text-white rounded-full w-6 h-6 flex items-center justify-center text-xs">2</div> Criar Tabelas (SQL)</h3>
           <p className="text-sm text-gray-500 mb-4">Copie o código abaixo e rode no <strong>SQL Editor</strong> do Supabase.</p>
           
           <div className="flex-1 bg-gray-900 rounded overflow-hidden relative mb-4">
              <button onClick={handleCopy} className="absolute top-2 right-2 bg-ocean-600 hover:bg-ocean-500 text-white px-2 py-1 rounded text-xs font-bold">{copied ? 'Copiado!' : 'Copiar'}</button>
              <pre className="p-4 text-xs text-green-400 font-mono h-32 overflow-auto">{SQL_SETUP_CODE}</pre>
           </div>
           
           <button onClick={handleVerify} disabled={checking} className="w-full bg-green-600 text-white py-3 rounded font-bold hover:bg-green-700 flex items-center justify-center gap-2 shadow-md">
             {checking ? <RefreshCw className="animate-spin" size={18}/> : <CheckCircle size={18}/>}
             Verificar Instalação e Concluir
           </button>
        </div>
      </div>
    </div>
  );
};

const PropertyDetails: React.FC<{ property: Property; onBack: () => void; bookingPhone: string; }> = ({ property, onBack, bookingPhone }) => {
  const [imgIdx, setImgIdx] = useState(0);
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const images = property.images && property.images.length > 0 ? property.images : ['https://via.placeholder.com/800x600?text=Sem+Foto'];
  
  // Tipos
  const isSeasonal = property.type === 'rent_seasonal';
  const isLongTerm = property.type === 'rent_longterm';
  
  const getDays = () => {
    if (!start || !end) return 0;
    const s = new Date(start);
    const e = new Date(end);
    const diff = e.getTime() - s.getTime();
    const days = Math.ceil(diff / (1000 * 3600 * 24));
    return days > 0 ? days : 0;
  };
  
  const days = getDays();
  const totalPrice = days * property.price;
  const pricePerPerson = (property.max_guests && property.max_guests > 0) ? (property.price / property.max_guests) : 0;

  const handleBook = () => {
    let msg = '';
    const phone = bookingPhone.replace(/\D/g, '');

    if (isSeasonal) {
      if (!start || !end) { alert("Por favor, selecione as datas."); return; }
      const formattedStart = new Date(start).toLocaleDateString('pt-BR');
      const formattedEnd = new Date(end).toLocaleDateString('pt-BR');
      const formattedTotal = new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(totalPrice);
      msg = `Olá! Gostaria de reservar *${property.title}*.\n📅 Check-in: ${formattedStart}\n📅 Check-out: ${formattedEnd}\n🌙 Diárias: ${days}\n💰 Total: ${formattedTotal}`;
    } else if (isLongTerm) {
      msg = `Olá! Tenho interesse na locação definitiva do imóvel *${property.title}* (R$ ${property.price}/mês). Gostaria de agendar uma visita ou saber mais sobre o contrato.`;
    } else {
      msg = `Olá! Tenho interesse em comprar o imóvel *${property.title}* (R$ ${property.price}).`;
    }
    window.open(`https://wa.me/${phone}?text=${encodeURIComponent(msg)}`, '_blank');
  };

  const getPriceLabel = () => {
    if (isSeasonal) return 'Valor por Noite';
    if (isLongTerm) return 'Valor Mensal';
    return 'Valor de Venda';
  };

  const getTypeBadge = () => {
    if (isSeasonal) return <span className="w-fit px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide text-white bg-green-500">Aluguel de Temporada</span>;
    if (isLongTerm) return <span className="w-fit px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide text-white bg-purple-500">Locação Definitiva</span>;
    return <span className="w-fit px-3 py-1 rounded-full text-xs font-bold uppercase tracking-wide text-white bg-blue-500">Venda</span>;
  }

  return (
    <div className="container mx-auto px-4 py-6">
      <button onClick={onBack} className="flex items-center text-muted hover:text-ocean-600 mb-4"><ArrowLeft size={20} className="mr-2"/> Voltar</button>
      <div className="relative h-[300px] md:h-[500px] bg-gray-100 rounded-2xl overflow-hidden mb-8 group shadow-lg">
        <img src={images[imgIdx]} alt={property.title} className="w-full h-full object-cover" />
        {images.length > 1 && (
          <>
            <button onClick={() => setImgIdx((prev) => (prev - 1 + images.length) % images.length)} className="absolute left-4 top-1/2 -translate-y-1/2 bg-black/40 hover:bg-black/60 p-3 rounded-full text-white"><ChevronLeft size={24}/></button>
            <button onClick={() => setImgIdx((prev) => (prev + 1) % images.length)} className="absolute right-4 top-1/2 -translate-y-1/2 bg-black/40 hover:bg-black/60 p-3 rounded-full text-white"><ChevronRight size={24}/></button>
            <div className="absolute bottom-6 right-6 bg-black/60 text-white px-4 py-1 rounded-full text-sm font-medium">{imgIdx + 1} / {images.length}</div>
          </>
        )}
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <div className="flex flex-col gap-2 mb-4">
            {getTypeBadge()}
            <div className="flex items-center gap-2">
              <h1 className="text-3xl font-bold text-main leading-tight">{property.title}</h1>
              {property.featured && <Star size={24} className="text-yellow-500 fill-yellow-500 flex-shrink-0"/>}
            </div>
            <div className="flex items-center text-muted"><MapPin size={18} className="mr-1" /> {property.location}</div>
          </div>
          
          <div className="flex gap-4 md:gap-8 border-y border-ocean-100 py-6 my-6 justify-center md:justify-start flex-wrap">
             <div className="text-center md:text-left"><div className="flex items-center justify-center md:justify-start gap-2 text-ocean-600 font-bold text-xl"><Bed/> {property.bedrooms}</div><span className="text-xs text-muted uppercase">Quartos</span></div>
             <div className="text-center md:text-left"><div className="flex items-center justify-center md:justify-start gap-2 text-ocean-600 font-bold text-xl"><Bath/> {property.bathrooms}</div><span className="text-xs text-muted uppercase">Banheiros</span></div>
             <div className="text-center md:text-left"><div className="flex items-center justify-center md:justify-start gap-2 text-ocean-600 font-bold text-xl"><Expand/> {property.area}</div><span className="text-xs text-muted uppercase">m² Úteis</span></div>
             {isSeasonal && property.max_guests && (
               <div className="text-center md:text-left"><div className="flex items-center justify-center md:justify-start gap-2 text-green-600 font-bold text-xl"><Users/> {property.max_guests}</div><span className="text-xs text-muted uppercase">Pessoas (Máx)</span></div>
             )}
          </div>
          
          <h3 className="text-lg font-bold mb-3">Sobre este imóvel</h3>
          <p className="whitespace-pre-line text-muted mb-8 leading-relaxed text-lg">{property.description}</p>
          <h3 className="text-lg font-bold mb-3">Características</h3>
          <div className="flex flex-wrap gap-2 mb-8">
            {property.features?.map((f, i) => <span key={i} className="bg-ocean-50 text-ocean-700 px-4 py-2 rounded-lg text-sm flex items-center font-medium"><CheckCircle size={16} className="mr-2 text-ocean-500"/>{f}</span>)}
          </div>
        </div>
        
        <div className="lg:col-span-1">
          <div className="bg-white border border-ocean-200 rounded-2xl p-6 shadow-xl sticky top-24">
             <div className="mb-6 pb-6 border-b border-ocean-100 text-center">
                <span className="text-4xl font-extrabold text-ocean-600 block mb-1">
                  {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(property.price)}
                </span>
                <span className="text-muted text-sm uppercase font-bold tracking-wide">{getPriceLabel()}</span>
                {isSeasonal && pricePerPerson > 0 && (
                  <div className="mt-2 text-sm bg-green-50 text-green-700 py-1 px-2 rounded-lg inline-block font-semibold">
                    Sai a {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(pricePerPerson)} por pessoa!
                  </div>
                )}
             </div>
             
             {isSeasonal ? (
               <div className="mb-2">
                 <div className="bg-ocean-50 p-4 rounded-xl mb-4 border border-ocean-100">
                    <h4 className="font-bold text-ocean-800 mb-3 flex items-center gap-2"><Calendar size={18}/> Planeje sua Estadia</h4>
                    <div className="space-y-3">
                       <div>
                          <label className="block text-xs font-bold uppercase text-muted mb-1 ml-1">Entrada</label>
                          <input type="date" className="w-full p-3 border border-ocean-200 rounded-lg bg-white" value={start} onChange={e => setStart(e.target.value)} />
                       </div>
                       <div>
                          <label className="block text-xs font-bold uppercase text-muted mb-1 ml-1">Saída</label>
                          <input type="date" className="w-full p-3 border border-ocean-200 rounded-lg bg-white" value={end} onChange={e => setEnd(e.target.value)} />
                       </div>
                    </div>
                 </div>
                 {days > 0 && (
                   <div className="bg-white border border-ocean-200 rounded-lg p-4 mb-4 shadow-sm">
                      <div className="flex justify-between items-center mb-2 text-sm text-gray-600">
                        <span>{new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(property.price)} x {days} noites</span>
                        <span>{new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(totalPrice)}</span>
                      </div>
                      <div className="border-t border-ocean-100 pt-3 mt-2 flex justify-between items-center font-bold text-xl text-ocean-800">
                        <span>Total</span>
                        <span>{new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(totalPrice)}</span>
                      </div>
                   </div>
                 )}
                 <button onClick={handleBook} className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-4 rounded-xl flex items-center justify-center gap-2 shadow-lg hover:scale-105 transition-transform"><Phone size={24} /> Reservar via WhatsApp</button>
               </div>
             ) : (
               <div className="mb-2">
                 {isLongTerm && (
                    <div className="bg-purple-50 p-4 rounded-xl mb-4 border border-purple-100 text-left">
                       <h4 className="font-bold text-purple-800 mb-2 flex items-center gap-2"><FileText size={18}/> Gestão Completa</h4>
                       <p className="text-sm text-purple-700 leading-relaxed">Cuidamos de toda a papelada, verificação de fiador e contrato para garantir sua segurança e tranquilidade.</p>
                    </div>
                 )}
                 <button onClick={handleBook} className={`w-full ${isLongTerm ? 'bg-purple-600 hover:bg-purple-700' : 'bg-ocean-600 hover:bg-ocean-700'} text-white font-bold py-4 rounded-xl flex items-center justify-center gap-2 shadow-lg hover:scale-105 transition-transform`}><Phone size={24} /> Falar com Corretor</button>
               </div>
             )}
          </div>
        </div>
      </div>
    </div>
  );
};

const AdminForm: React.FC<{ property?: Property | null; onSave: (p: Partial<Property>) => Promise<void>; onCancel: () => void; }> = ({ property, onSave, onCancel }) => {
  const [formData, setFormData] = useState<Partial<Property>>(property || { 
    type: 'sale', features: [], images: [], active: true, featured: false, owner_notes: '', max_guests: 0
  });
  const [loading, setLoading] = useState(false);
  const [imgUrl, setImgUrl] = useState('');
  const [newFeature, setNewFeature] = useState('');
  const [uploading, setUploading] = useState(false);

  const handleGenerateDesc = async () => {
    setLoading(true);
    const desc = await generatePropertyDescription({
      title: formData.title,
      location: formData.location,
      type: formData.type,
      bedrooms: formData.bedrooms,
      bathrooms: formData.bathrooms,
      area: formData.area,
      price: formData.price,
      features: formData.features
    });
    setFormData(prev => ({ ...prev, description: desc }));
    setLoading(false);
  };

  const addImage = () => { if (imgUrl) { setFormData(prev => ({ ...prev, images: [...(prev.images || []), imgUrl] })); setImgUrl(''); }};
  const removeImage = (idx: number) => setFormData(prev => ({ ...prev, images: prev.images?.filter((_, i) => i !== idx) }));
  
  const handleFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
       setUploading(true);
       const url = await uploadImage(e.target.files[0]);
       if (url) setFormData(prev => ({ ...prev, images: [...(prev.images || []), url] }));
       setUploading(false);
       e.target.value = '';
    }
  };

  const addFeature = () => { if (newFeature.trim()) { setFormData(prev => ({ ...prev, features: [...(prev.features || []), newFeature.trim()] })); setNewFeature(''); }};
  const removeFeature = (index: number) => { setFormData(prev => ({ ...prev, features: prev.features?.filter((_, i) => i !== index) })); };
  const handleFeatureKey = (e: React.KeyboardEvent) => { if (e.key === 'Enter') { e.preventDefault(); addFeature(); }};

  return (
    <div className="container mx-auto p-4 max-w-3xl">
      <div className="flex items-center mb-6 text-ocean-600 cursor-pointer" onClick={onCancel}><ArrowLeft className="mr-2" /> Voltar</div>
      <h2 className="text-2xl font-bold mb-6">{property ? 'Editar Imóvel' : 'Novo Imóvel'}</h2>
      <div className="bg-white p-6 rounded-xl shadow-sm border border-ocean-100 space-y-4">
        
        <div className="flex gap-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
           <label className="flex items-center gap-2 cursor-pointer"><input type="checkbox" checked={formData.active !== false} onChange={e => setFormData({ ...formData, active: e.target.checked })} className="w-5 h-5 accent-ocean-600"/><span className="font-bold flex items-center gap-1">{formData.active !== false ? <Eye size={16}/> : <EyeOff size={16}/>} Visível</span></label>
           <div className="w-px bg-gray-300"></div>
           <label className="flex items-center gap-2 cursor-pointer text-yellow-600"><input type="checkbox" checked={formData.featured || false} onChange={e => setFormData({ ...formData, featured: e.target.checked })} className="w-5 h-5 accent-yellow-500"/><span className="font-bold flex items-center gap-1"><Star size={16}/> Destaque</span></label>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div>
            <label className="block text-sm font-bold text-muted mb-1">Tipo de Anúncio</label>
            <select className="w-full p-2 border rounded" value={formData.type} onChange={e => setFormData({ ...formData, type: e.target.value as any })}>
              <option value="sale">Venda</option>
              <option value="rent_seasonal">Aluguel Temporada</option>
              <option value="rent_longterm">Locação Definitiva (Mensal)</option>
            </select>
          </div>
          <div><label className="block text-sm font-bold text-muted mb-1">Título</label><input placeholder="Ex: Casa Linda" className="w-full p-2 border rounded" value={formData.title || ''} onChange={e => setFormData({ ...formData, title: e.target.value })} /></div>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <div><label className="block text-sm font-bold text-muted mb-1">Localização</label><input placeholder="Ex: Itamambuca" className="w-full p-2 border rounded" value={formData.location || ''} onChange={e => setFormData({ ...formData, location: e.target.value })} /></div>
          <div><label className="block text-sm font-bold text-muted mb-1">Preço (R$)</label><input type="number" className="w-full p-2 border rounded" value={formData.price || ''} onChange={e => setFormData({ ...formData, price: Number(e.target.value) })} /></div>
        </div>

        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
           <div><label className="block text-sm font-bold text-muted mb-1">Quartos</label><input type="number" className="w-full p-2 border rounded" value={formData.bedrooms || ''} onChange={e => setFormData({ ...formData, bedrooms: Number(e.target.value) })} /></div>
           <div><label className="block text-sm font-bold text-muted mb-1">Banheiros</label><input type="number" className="w-full p-2 border rounded" value={formData.bathrooms || ''} onChange={e => setFormData({ ...formData, bathrooms: Number(e.target.value) })} /></div>
           <div><label className="block text-sm font-bold text-muted mb-1">Área (m²)</label><input type="number" className="w-full p-2 border rounded" value={formData.area || ''} onChange={e => setFormData({ ...formData, area: Number(e.target.value) })} /></div>
           <div className={formData.type === 'rent_seasonal' ? 'bg-green-50 p-1 rounded' : ''}>
              <label className="block text-sm font-bold text-muted mb-1 flex items-center gap-1"><Users size={14}/> Máx. Pessoas</label>
              <input type="number" className="w-full p-2 border rounded" value={formData.max_guests || ''} onChange={e => setFormData({ ...formData, max_guests: Number(e.target.value) })} placeholder="0" />
           </div>
        </div>

        <div>
           <label className="block text-sm font-bold text-muted mb-1">Características (Tag)</label>
           <div className="flex gap-2 mb-2">
              <input className="flex-1 p-2 border rounded" placeholder="Digite e aperte Enter..." value={newFeature} onChange={e => setNewFeature(e.target.value)} onKeyDown={handleFeatureKey} />
              <button onClick={addFeature} className="bg-ocean-100 text-ocean-600 px-4 rounded font-bold"><Plus/></button>
           </div>
           <div className="flex flex-wrap gap-2">{formData.features?.map((f, i) => <span key={i} className="bg-ocean-50 text-ocean-700 px-3 py-1 rounded-full text-sm flex items-center gap-1 border border-ocean-100">{f}<button onClick={() => removeFeature(i)} className="text-red-500 rounded-full"><X size={14}/></button></span>)}</div>
        </div>

        <div><label className="block text-sm font-bold text-muted mb-1">Anotações Internas</label><input className="w-full p-2 border border-yellow-200 bg-yellow-50 rounded text-sm" value={formData.owner_notes || ''} onChange={e => setFormData({ ...formData, owner_notes: e.target.value })} /></div>

        <div>
          <label className="block text-sm font-bold text-muted mb-1">Fotos</label>
          <div className="flex gap-2 mb-2">
            <label className={`bg-ocean-600 text-white px-4 py-2 rounded cursor-pointer flex items-center gap-2 hover:bg-ocean-700 ${uploading ? 'opacity-50' : ''}`}>
              {uploading ? <RefreshCw className="animate-spin" size={20}/> : <Upload size={20}/>}<span>Upload</span><input type="file" hidden onChange={handleFile} accept="image/*" disabled={uploading}/>
            </label>
          </div>
          <div className="flex gap-2 overflow-x-auto py-2">{formData.images?.map((img, i) => <div key={i} className="relative w-20 h-20 flex-shrink-0 border rounded overflow-hidden"><img src={img} className="w-full h-full object-cover" /><button onClick={() => removeImage(i)} className="absolute top-0 right-0 bg-red-600 text-white p-0.5"><X size={12}/></button></div>)}</div>
        </div>
        
        <div><label className="block text-sm font-bold text-muted mb-1">Descrição</label><textarea rows={5} className="w-full p-2 border rounded" value={formData.description || ''} onChange={e => setFormData({ ...formData, description: e.target.value })} /></div>
        
        <div className="flex gap-2 justify-end">
          <button onClick={handleGenerateDesc} disabled={loading} className="flex items-center gap-2 text-ocean-600 bg-ocean-50 px-4 py-2 rounded hover:bg-ocean-100 border border-ocean-200">{loading ? 'Criando...' : 'Gerar com IA'}</button>
          <button onClick={() => onSave(formData)} className="bg-ocean-600 text-white px-6 py-2 rounded hover:bg-ocean-700 shadow-md">Salvar</button>
        </div>
      </div>
    </div>
  );
};

const AdminSettings: React.FC<{ settings: SiteSettings; onSave: (s: SiteSettings) => void }> = ({ settings, onSave }) => {
  const [local, setLocal] = useState(settings);
  const [uploading, setUploading] = useState(false);
  const handleFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
       setUploading(true);
       const url = await uploadImage(e.target.files[0]);
       if (url) setLocal({ ...local, logoUrl: url });
       setUploading(false); e.target.value = '';
    }
  };
  return (
    <div className="container mx-auto p-4 max-w-4xl">
      <div className="flex items-center mb-6"><h2 className="text-2xl font-bold flex items-center gap-2"><Settings/> Configurações</h2></div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="space-y-4 bg-white p-6 rounded-xl border border-ocean-100">
           <h3 className="font-bold mb-4 flex items-center gap-2"><Palette/> Aparência</h3>
           <label className="block text-sm mb-1">Nome do Site</label><input className="w-full p-2 border rounded mb-3" value={local.siteName} onChange={e => setLocal({ ...local, siteName: e.target.value })} />
           <label className="block text-sm mb-1">Logo</label>
           <div className="flex gap-2 mb-3">
             <input className="flex-1 p-2 border rounded" value={local.logoUrl || ''} onChange={e => setLocal({ ...local, logoUrl: e.target.value })} />
             <label className="bg-gray-200 px-3 py-2 rounded cursor-pointer">{uploading ? <RefreshCw className="animate-spin"/> : <Upload/>}<input type="file" hidden onChange={handleFile}/></label>
           </div>
           <label className="block text-sm mb-1">Tema</label>
           <div className="grid grid-cols-4 gap-2">{['ocean', 'nature', 'sunset', 'dark'].map((c) => <button key={c} onClick={() => setLocal({ ...local, primaryColor: c as any })} className={`h-8 rounded-full border-2 ${local.primaryColor === c ? 'border-black' : 'border-transparent'}`} style={{ background: c === 'ocean' ? '#0ea5e9' : c === 'nature' ? '#22c55e' : c === 'sunset' ? '#ef4444' : '#333' }} />)}</div>
        </div>
        <div className="space-y-4 bg-white p-6 rounded-xl border border-ocean-100">
           <h3 className="font-bold mb-4 flex items-center gap-2"><Phone/> Contato</h3>
           <label className="block text-sm mb-1">WhatsApp Principal</label><input className="w-full p-2 border rounded mb-3" value={local.contact.phone} onChange={e => setLocal({ ...local, contact: { ...local.contact, phone: maskPhone(e.target.value) } })} />
           <label className="block text-sm mb-1">WhatsApp Reservas</label><input className="w-full p-2 border rounded mb-3" value={local.contact.bookingPhone || ''} onChange={e => setLocal({ ...local, contact: { ...local.contact, bookingPhone: maskPhone(e.target.value) } })} />
           <label className="block text-sm mb-1">Instagram</label><input className="w-full p-2 border rounded mb-3" value={local.social.instagram} onChange={e => setLocal({ ...local, social: { ...local.social, instagram: e.target.value } })} />
           <label className="block text-sm mb-1">Facebook</label><input className="w-full p-2 border rounded mb-3" value={local.social.facebook} onChange={e => setLocal({ ...local, social: { ...local.social, facebook: e.target.value } })} />
           <label className="block text-sm mb-1">Horários</label><input className="w-full p-2 border rounded mb-3" value={local.contact.hours} onChange={e => setLocal({ ...local, contact: { ...local.contact, hours: e.target.value } })} />
        </div>
      </div>
      <div className="mt-6 flex justify-end gap-2">
         {localStorage.getItem('sb_url') && (
           <button onClick={() => { if(confirm("Deseja desconectar o projeto atual?")) resetSupabaseCredentials(); }} className="bg-red-50 text-red-600 py-3 px-6 rounded-xl font-bold hover:bg-red-100 flex gap-2"><Database size={20}/> Trocar Projeto DB</button>
         )}
         <button onClick={() => onSave(local)} className="bg-ocean-600 text-white py-3 px-8 rounded-xl font-bold hover:bg-ocean-700 flex gap-2"><Save/> Salvar</button>
      </div>
    </div>
  );
};

const AppContent: React.FC = () => {
  const [properties, setProperties] = useState<Property[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [settings, setSettings] = useState<SiteSettings>(INITIAL_SETTINGS);
  const [view, setView] = useState<ViewState>(ViewState.HOME);
  const [selectedProperty, setSelectedProperty] = useState<Property | null>(null);
  const [dbError, setDbError] = useState<string | null>(null);
  const [logoFailed, setLogoFailed] = useState(false);
  const [showDbSetup, setShowDbSetup] = useState(false);
  const [showLoginModal, setShowLoginModal] = useState(false);
  
  // Tipos: 'all', 'sale', 'rent_seasonal', 'rent_longterm'
  const [filterType, setFilterType] = useState<'all' | 'sale' | 'rent_seasonal' | 'rent_longterm'>('all');
  const [locationFilter, setLocationFilter] = useState('');
  const [priceRange, setPriceRange] = useState<{max: number}>({max: 0});
  const [minBedrooms, setMinBedrooms] = useState(0);

  const loadingTimeoutRef = useRef<any>(null);

  useLayoutEffect(() => { const loader = document.getElementById('loading-screen'); if (loader) loader.style.display = 'none'; }, []);

  useEffect(() => {
    const cachedSettings = localStorage.getItem('site_settings_cache');
    if (cachedSettings) { try { setSettings(JSON.parse(cachedSettings)); } catch (e) {} }
    fetchSettings(); fetchProperties();
    return () => { if (loadingTimeoutRef.current) clearTimeout(loadingTimeoutRef.current); };
  }, []);

  useEffect(() => { document.body.className = `bg-page text-main transition-colors duration-300 theme-${settings.primaryColor}`; }, [settings]);
  useEffect(() => { setLogoFailed(false); }, [settings.logoUrl]);

  const fetchSettings = async () => {
    try {
      const { data, error } = await supabase.from('site_settings').select('data').single();
      if (error && error.code === '42P01') { setShowDbSetup(true); } 
      else if (data?.data) {
        setSettings({ ...INITIAL_SETTINGS, ...data.data });
        localStorage.setItem('site_settings_cache', JSON.stringify({ ...INITIAL_SETTINGS, ...data.data }));
      }
    } catch (e) { console.log(e); }
  };

  const fetchProperties = async () => {
    setIsLoading(true); setDbError(null);
    loadingTimeoutRef.current = setTimeout(() => { if (isLoading) { setIsLoading(false); setDbError("Conexão lenta."); } }, 8000);
    try {
      const { data, error } = await supabase.from('properties').select('*').order('featured', { ascending: false, nullsLast: true }).order('created_at', { ascending: false });
      if (loadingTimeoutRef.current) clearTimeout(loadingTimeoutRef.current);
      if (error) { if (error.code === '42P01') setShowDbSetup(true); else setDbError(error.message); }
      else if (data) {
        setProperties(data.map((p: any) => ({ ...p, images: p.images || [], features: p.features || [], active: p.active !== false, featured: p.featured === true, max_guests: p.max_guests || 0 })));
      }
    } catch (err: any) { setDbError("Erro de conexão."); }
    setIsLoading(false);
  };

  const handleSaveSettings = async (newSettings: SiteSettings) => {
    setSettings(newSettings); localStorage.setItem('site_settings_cache', JSON.stringify(newSettings));
    const { error } = await supabase.from('site_settings').upsert({ id: 1, data: newSettings });
    if (error) { if (error.code === '42P01') setShowDbSetup(true); else alert("Erro ao salvar no banco: " + error.message); } else alert("Salvo!");
  };

  const handleSaveProperty = async (p: Partial<Property>) => {
    const { error } = p.id ? await supabase.from('properties').update(p).eq('id', p.id) : await supabase.from('properties').insert(p);
    if (error) alert("Erro: " + error.message); else { fetchProperties(); setView(ViewState.ADMIN_PROPERTIES); }
  };

  const handleDelete = async (id: string) => {
    if (confirm("Excluir?")) {
      const { error } = await supabase.from('properties').delete().eq('id', id);
      if (error) alert("Erro: " + error.message); else { alert("Excluído!"); fetchProperties(); }
    }
  };

  const visibleProperties = properties.filter(p => {
    if (view === ViewState.ADMIN_PROPERTIES) return true;
    if (p.active === false) return false;
    
    // Filtragem de Tipo aprimorada
    let matchesType = filterType === 'all';
    if (!matchesType) {
      if (filterType === 'rent_seasonal') matchesType = p.type === 'rent_seasonal' || p.type === 'temporada';
      else if (filterType === 'rent_longterm') matchesType = p.type === 'rent_longterm';
      else if (filterType === 'sale') matchesType = p.type === 'sale' || p.type === 'venda';
    }

    const matchesLocation = locationFilter === '' || p.location.toLowerCase().includes(locationFilter.toLowerCase()) || p.title.toLowerCase().includes(locationFilter.toLowerCase());
    const matchesBedrooms = minBedrooms === 0 || p.bedrooms >= minBedrooms;
    const matchesPrice = priceRange.max === 0 || p.price <= priceRange.max;
    return matchesType && matchesLocation && matchesBedrooms && matchesPrice;
  });

  if (showDbSetup) return <DatabaseSetup />;

  return (
    <div className="min-h-screen bg-page font-sans text-main flex flex-col">
      <AdminLoginModal isOpen={showLoginModal} onClose={() => setShowLoginModal(false)} onLogin={() => { setShowLoginModal(false); setView(ViewState.ADMIN_PROPERTIES); }} />
      <header className="bg-card shadow-sm sticky top-0 z-50 border-b border-ocean-100 h-16 flex items-center justify-between px-2 md:px-4 shrink-0">
         <div className="flex items-center gap-3 font-bold text-xl cursor-pointer" onClick={() => setView(ViewState.HOME)}>
            {settings.logoUrl && !logoFailed ? (<img src={settings.logoUrl} className="h-10 w-auto md:h-12" onError={() => setLogoFailed(true)} />) : <UbatubaLogo className="h-10 w-10 md:h-12 md:w-12" />}
            <span className="text-sm md:text-xl text-ocean-800">{settings.siteName}</span>
         </div>
         <div className="flex gap-2">
           <button onClick={() => view === ViewState.HOME ? setShowLoginModal(true) : setView(ViewState.HOME)} className="px-3 py-1 md:px-4 md:py-2 border rounded-full hover:bg-ocean-50 text-ocean-700 flex gap-1 md:gap-2 text-xs md:text-sm font-medium items-center">
             {view === ViewState.HOME ? <><UserCircle size={16}/> Admin</> : <><Globe size={16}/> Site</>}
           </button>
         </div>
      </header>
      <main className="flex-1">
        {dbError && <div className="container mx-auto p-4 mt-4"><div className="bg-red-100 text-red-800 p-4 rounded border border-red-200 flex justify-between items-center"><span className="flex items-center gap-2"><AlertTriangle size={16}/> <strong>Erro:</strong> {dbError}</span><button onClick={fetchProperties} className="bg-red-200 px-3 py-1 rounded">Tentar</button></div></div>}
        {view === ViewState.HOME && (
          <>
            <div className="bg-ocean-50 py-4 md:py-8 border-b border-ocean-100">
               <div className="container mx-auto px-2 md:px-4">
                 <div className="grid grid-cols-2 md:flex md:flex-wrap justify-center gap-2 md:gap-4 mb-4">
                    <button onClick={() => setFilterType('all')} className={`px-3 py-2 md:px-6 md:py-3 rounded-full font-bold text-xs md:text-lg ${filterType === 'all' ? 'bg-ocean-600 text-white' : 'bg-white text-ocean-600 border border-ocean-200'}`}>Todos</button>
                    <button onClick={() => setFilterType('rent_seasonal')} className={`px-3 py-2 md:px-6 md:py-3 rounded-full font-bold text-xs md:text-lg ${filterType === 'rent_seasonal' ? 'bg-green-600 text-white' : 'bg-white text-green-600 border border-ocean-200'}`}>Temporada</button>
                    <button onClick={() => setFilterType('rent_longterm')} className={`px-3 py-2 md:px-6 md:py-3 rounded-full font-bold text-xs md:text-lg ${filterType === 'rent_longterm' ? 'bg-purple-600 text-white' : 'bg-white text-purple-600 border border-ocean-200'}`}>Anual</button>
                    <button onClick={() => setFilterType('sale')} className={`px-3 py-2 md:px-6 md:py-3 rounded-full font-bold text-xs md:text-lg ${filterType === 'sale' ? 'bg-blue-600 text-white' : 'bg-white text-blue-600 border border-ocean-200'}`}>Comprar</button>
                 </div>
                 <div className="bg-white p-3 md:p-4 rounded-xl shadow-sm border border-ocean-100 max-w-4xl mx-auto flex flex-col md:flex-row gap-3 items-center">
                    <div className="relative flex-1 w-full"><MapPin size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted"/><input className="w-full pl-10 pr-4 py-2 border rounded-lg text-sm" placeholder="Bairro..." value={locationFilter} onChange={e => setLocationFilter(e.target.value)}/></div>
                    <div className="flex w-full md:w-auto gap-2">
                       <div className="relative flex-1 md:w-32"><Bed size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted"/><input type="number" className="w-full pl-10 pr-4 py-2 border rounded-lg text-sm" placeholder="Quartos+" value={minBedrooms || ''} onChange={e => setMinBedrooms(Number(e.target.value))}/></div>
                       <div className="relative flex-1 md:w-36"><span className="absolute left-3 top-1/2 -translate-y-1/2 text-muted text-sm">R$</span><input type="number" className="w-full pl-8 pr-4 py-2 border rounded-lg text-sm" placeholder="Máximo..." value={priceRange.max || ''} onChange={e => setPriceRange({max: Number(e.target.value)})}/></div>
                    </div>
                    {(locationFilter || minBedrooms > 0 || priceRange.max > 0) && <button onClick={() => { setLocationFilter(''); setMinBedrooms(0); setPriceRange({max: 0}); }} className="p-2 text-red-500 hover:bg-red-50 rounded-full"><X size={18}/></button>}
                 </div>
               </div>
            </div>
            <div className="container mx-auto px-4 py-8">
              {isLoading ? <LoadingSpinner /> : (
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                  {visibleProperties.map(p => (<div key={p.id} className="relative group">{p.featured && <div className="absolute -top-3 left-4 z-10 bg-yellow-500 text-white px-3 py-1 rounded-full text-xs font-bold shadow flex items-center gap-1"><Star size={12}/> DESTAQUE</div>}<PropertyCard property={p} onClick={() => { setSelectedProperty(p); setView(ViewState.DETAILS); }} /></div>))}
                  {visibleProperties.length === 0 && !dbError && <div className="col-span-full text-center py-12 text-muted"><Filter size={48} className="mx-auto mb-4 text-ocean-200" /><p>Nenhum imóvel encontrado.</p></div>}
                </div>
              )}
            </div>
          </>
        )}
        {view === ViewState.DETAILS && selectedProperty && <PropertyDetails property={selectedProperty} onBack={() => setView(ViewState.HOME)} bookingPhone={settings.contact.bookingPhone || settings.contact.phone} />}
        {view === ViewState.ADMIN_PROPERTIES && (
           <div className="container mx-auto p-4 flex flex-col md:flex-row gap-6">
              <div className="w-full md:w-64 flex flex-row md:flex-col gap-2 overflow-x-auto pb-2 md:pb-0 sticky top-20 h-fit z-10 bg-page">
                  <button className="flex-1 bg-ocean-600 text-white p-3 rounded text-left font-bold flex gap-2"><LayoutDashboard size={18}/> Imóveis</button>
                  <button onClick={() => setView(ViewState.ADMIN_SETTINGS)} className="flex-1 bg-white text-muted p-3 rounded text-left hover:bg-gray-50 flex gap-2"><Settings size={18}/> Configurações</button>
              </div>
              <div className="flex-1">
                <div className="flex justify-between items-center mb-6"><h1 className="text-2xl font-bold text-ocean-800">Meus Imóveis</h1><button onClick={() => { setSelectedProperty(null); setView(ViewState.ADMIN_FORM); }} className="bg-ocean-600 text-white px-4 py-2 rounded-full hover:bg-ocean-700 flex items-center gap-2 font-bold shadow-lg"><Plus size={20}/> Novo Imóvel</button></div>
                {isLoading ? <LoadingSpinner /> : (
                  <div className="grid grid-cols-1 gap-4">
                    {properties.map(p => (
                      <div key={p.id} className={`bg-white p-4 rounded-lg shadow flex justify-between items-center ${p.active === false ? 'opacity-60 bg-gray-50' : ''} ${p.featured ? 'border-l-4 border-yellow-400' : ''}`}>
                          <div className="flex items-center gap-4"><img src={p.images[0] || 'https://via.placeholder.com/50'} className="w-16 h-16 object-cover rounded" /><div><div className="flex items-center gap-2"><h3 className="font-bold">{p.title}</h3>{p.active === false && <span className="text-xs bg-gray-200 text-gray-600 px-2 rounded">Inativo</span>}{p.featured && <Star size={14} className="text-yellow-500 fill-yellow-500"/>}</div><p className="text-sm text-muted">{p.location}</p></div></div>
                          <div className="flex gap-2"><button onClick={() => { setSelectedProperty(p); setView(ViewState.ADMIN_FORM); }} className="p-2 text-blue-600 hover:bg-blue-50 rounded"><Edit size={18}/></button><button onClick={() => handleDelete(p.id)} className="p-2 text-red-600 hover:bg-red-50 rounded"><Trash2 size={18}/></button></div>
                      </div>
                    ))}
                    {properties.length === 0 && <div className="text-center text-muted py-8">Nenhum imóvel.</div>}
                  </div>
                )}
              </div>
           </div>
        )}
        {view === ViewState.ADMIN_FORM && <AdminForm property={selectedProperty} onSave={handleSaveProperty} onCancel={() => setView(ViewState.ADMIN_PROPERTIES)} />}
        {view === ViewState.ADMIN_SETTINGS && <div className="container mx-auto p-4"><button onClick={() => setView(ViewState.ADMIN_PROPERTIES)} className="mb-4 flex items-center text-muted hover:text-ocean-600"><ArrowLeft size={18} className="mr-2"/> Voltar</button><AdminSettings settings={settings} onSave={handleSaveSettings} /></div>}
      </main>
      {(view === ViewState.HOME || view === ViewState.DETAILS) && <Footer settings={settings} />}
    </div>
  );
};

const App: React.FC = () => <ErrorBoundary><AppContent /></ErrorBoundary>;
export default App;