import React, { useState, useEffect, useRef, useLayoutEffect } from 'react';
import { Property, ViewState, SiteSettings } from './types';
import { generatePropertyDescription } from './services/geminiService';
import { supabase } from './services/supabaseClient';
import { PropertyCard } from './components/PropertyCard';
import { 
  LayoutDashboard, Plus, Settings, Phone, Palette, Save, Trash2, 
  Image as ImageIcon, Edit, UserCircle, Globe, Database,
  ArrowLeft, X, Camera, Sparkles, MapPin, Bed, Bath, Expand, CheckCircle,
  AlertTriangle, RefreshCw, ChevronLeft, ChevronRight, Upload,
  Eye, EyeOff, Star, FileText
} from 'lucide-react';

// --- ERROR BOUNDARY ---
interface ErrorBoundaryProps { children?: React.ReactNode; }
interface ErrorBoundaryState { hasError: boolean; error: Error | null; }

class ErrorBoundary extends React.Component<ErrorBoundaryProps, ErrorBoundaryState> {
  constructor(props: ErrorBoundaryProps) {
    super(props);
    this.state = { hasError: false, error: null };
  }

  static getDerivedStateFromError(error: Error): ErrorBoundaryState {
    return { hasError: true, error };
  }

  render() {
    if (this.state.hasError) {
      const loader = document.getElementById('loading-screen');
      if (loader) loader.style.display = 'none';

      return (
        <div className="min-h-screen flex items-center justify-center bg-red-50 p-4 text-center">
          <div className="bg-white p-8 rounded-xl shadow-lg max-w-lg">
            <AlertTriangle size={48} className="mx-auto text-red-600 mb-4" />
            <h1 className="text-xl font-bold text-red-700 mb-2">Erro de Renderização</h1>
            <p className="text-gray-600 mb-4">Ocorreu um erro ao exibir a interface.</p>
            <pre className="bg-gray-100 p-2 rounded text-xs text-left overflow-auto mb-4 max-h-40">
              {this.state.error?.message}
            </pre>
            <button onClick={() => window.location.reload()} className="bg-red-600 text-white px-4 py-2 rounded">Recarregar</button>
          </div>
        </div>
      );
    }
    return this.props.children;
  }
}

// --- UTILS ---
const maskPhone = (value: string) => value.replace(/\D/g, '').replace(/(\d{2})(\d)/, '($1) $2').replace(/(\d{5})(\d)/, '$1-$2').replace(/(-\d{4})\d+?$/, '$1');
const fileToBase64 = (file: File): Promise<string> => new Promise((resolve, reject) => {
  const reader = new FileReader();
  reader.readAsDataURL(file);
  reader.onload = () => resolve(reader.result as string);
  reader.onerror = error => reject(error);
});

// --- SQL SETUP (ATUALIZADO PARA CAMPOS NOVOS) ---
const SQL_SETUP_CODE = `-- 1. CRIAR TABELA DE IMÓVEIS (SE NÃO EXISTIR)
create table if not exists properties (
  id uuid default gen_random_uuid() primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  location text,
  price numeric,
  type text, -- 'sale' ou 'rent_seasonal'
  bedrooms integer,
  bathrooms integer,
  area numeric,
  features text[], -- Lista de características
  images text[],   -- Lista de fotos
  views integer default 0,
  -- Campos Administrativos Novos
  active boolean default true,     -- Para ocultar imóvel sem deletar
  featured boolean default false,  -- Para colocar em destaque
  owner_notes text                 -- Anotações internas (ex: contato do dono)
);

-- 2. MIGRAÇÃO: ADICIONAR COLUNAS NOVAS (SE A TABELA JÁ EXISTIR)
-- Isso garante que quem já tem o banco criado receba os novos campos sem perder dados
do $$
begin
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='active') then
    alter table properties add column active boolean default true;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='featured') then
    alter table properties add column featured boolean default false;
  end if;
  if not exists (select 1 from information_schema.columns where table_name='properties' and column_name='owner_notes') then
    alter table properties add column owner_notes text;
  end if;
end
$$;

-- 3. TABELA DE CONFIGURAÇÕES (PARA SALVAR CORES, LOGO E TELEFONE)
create table if not exists site_settings (
  id int primary key generated by default as identity,
  data jsonb not null
);

-- Garante que existe pelo menos uma linha de configuração inicial
insert into site_settings (id, data) values (1, '{}'::jsonb) on conflict (id) do nothing;

-- 4. LIBERAR ACESSO (PERMISSÕES/RLS)
-- Primeiro habilita a segurança
alter table properties enable row level security;
alter table site_settings enable row level security;

-- Remove políticas antigas para evitar erros de duplicidade
drop policy if exists "Public Access" on properties;
drop policy if exists "Public Settings" on site_settings;

-- Cria políticas liberando leitura e escrita para o aplicativo
create policy "Public Access" on properties for all using (true) with check (true);
create policy "Public Settings" on site_settings for all using (true) with check (true);
`;

const UbatubaLogo: React.FC<{ className?: string }> = ({ className }) => (
  <svg viewBox="0 0 200 200" className={className} fill="none" xmlns="http://www.w3.org/2000/svg">
    <circle cx="100" cy="100" r="95" stroke="currentColor" strokeWidth="8" className="text-ocean-600" fill="white"/>
    <path d="M30 90 L100 40 L170 90" stroke="currentColor" strokeWidth="8" strokeLinecap="round" className="text-ocean-800"/>
    <path d="M55 72 L55 55 L65 55 L65 65" stroke="currentColor" strokeWidth="6" className="text-ocean-800"/>
    <rect x="60" y="90" width="20" height="20" fill="currentColor" className="text-ocean-800"/>
    <rect x="120" y="90" width="20" height="20" fill="currentColor" className="text-ocean-800"/>
    <text x="100" y="135" textAnchor="middle" fontFamily="Arial, sans-serif" fontWeight="900" fontSize="28" fill="black" letterSpacing="-1">ALUGA-SE</text>
    <text x="100" y="160" textAnchor="middle" fontFamily="Arial, sans-serif" fontWeight="900" fontSize="28" className="fill-ocean-600" letterSpacing="-1">UBATUBA</text>
    <text x="160" y="175" textAnchor="end" fontFamily="Arial, sans-serif" fontWeight="bold" fontSize="12" className="fill-ocean-600">.COM</text>
    <path d="M20 115 Q 50 105, 80 115 T 140 115 T 180 105" stroke="currentColor" strokeWidth="4" fill="none" className="text-ocean-400"/>
  </svg>
);

const INITIAL_SETTINGS: SiteSettings = {
  siteName: 'Aluga-se Ubatuba',
  logoUrl: '/img/LOGO_LEGAL.png', 
  primaryColor: 'ocean',
  contact: {
    address: 'Av. Leovigildo Dias Vieira, 1000 - Itaguá',
    phone: '(12) 99999-9999',
    bookingPhone: '(12) 98888-8888', 
    email: 'contato@alugaseubatuba.com.br',
    hours: 'Seg a Sex: 09h - 18h | Sáb: 09h - 13h'
  },
  social: { instagram: '@alugaseubatuba', facebook: '/alugaseubatuba' }
};

// --- COMPONENTES ---

const DatabaseSetup: React.FC = () => {
  const [copied, setCopied] = useState(false);
  const handleCopy = () => {
    navigator.clipboard.writeText(SQL_SETUP_CODE);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  return (
    <div className="container mx-auto px-4 py-12 flex flex-col items-center justify-center min-h-[60vh] text-center">
      <div className="bg-red-50 text-red-600 p-4 rounded-full mb-6"><AlertTriangle size={48} /></div>
      <h1 className="text-2xl md:text-3xl font-bold text-main mb-4">Atualização de Banco de Dados</h1>
      <p className="text-muted max-w-2xl mb-8">
        Detectamos que seu banco precisa de atualização (novos campos de status/destaque).<br/>
        Copie o SQL abaixo e rode no Supabase para garantir que tudo funcione.
      </p>
      <div className="w-full max-w-3xl bg-gray-900 rounded-xl overflow-hidden shadow-2xl text-left mb-6">
        <div className="bg-gray-800 px-4 py-2 flex justify-between items-center border-b border-gray-700">
          <span className="text-gray-400 text-sm font-mono">SQL</span>
          <button onClick={handleCopy} className="text-white hover:text-ocean-300 text-sm font-medium">{copied ? 'Copiado!' : 'Copiar SQL'}</button>
        </div>
        <pre className="p-6 overflow-x-auto text-sm text-green-400 font-mono"><code>{SQL_SETUP_CODE}</code></pre>
      </div>
      <button onClick={() => window.location.reload()} className="bg-ocean-600 text-white px-8 py-3 rounded-full font-bold hover:bg-ocean-700 flex items-center gap-2"><RefreshCw size={20} /> Já Rodei o SQL, Recarregar</button>
    </div>
  );
};

const PropertyDetails: React.FC<{ property: Property; onBack: () => void; bookingPhone: string; }> = ({ property, onBack, bookingPhone }) => {
  const [imgIdx, setImgIdx] = useState(0);
  const [start, setStart] = useState('');
  const [end, setEnd] = useState('');
  const images = property.images && property.images.length > 0 ? property.images : ['https://via.placeholder.com/800x600?text=Sem+Foto'];
  
  const calcTotal = () => {
    if (!start || !end) return 0;
    const diff = Math.ceil(Math.abs(new Date(end).getTime() - new Date(start).getTime()) / (1000 * 3600 * 24));
    return diff * property.price;
  };

  const handleBook = () => {
    const msg = property.type === 'rent_seasonal' 
      ? `Olá! Gostaria de reservar "${property.title}" de ${start} a ${end}.` 
      : `Olá! Tenho interesse em comprar "${property.title}".`;
    window.open(`https://wa.me/${bookingPhone.replace(/\D/g, '')}?text=${encodeURIComponent(msg)}`, '_blank');
  };

  return (
    <div className="container mx-auto px-4 py-6">
      <button onClick={onBack} className="flex items-center text-muted hover:text-ocean-600 mb-4"><ArrowLeft size={20} className="mr-2"/> Voltar</button>
      <div className="relative h-[300px] md:h-[500px] bg-gray-100 rounded-2xl overflow-hidden mb-8 group">
        <img src={images[imgIdx]} alt={property.title} className="w-full h-full object-cover" />
        {images.length > 1 && (
          <>
            <button onClick={() => setImgIdx((prev) => (prev - 1 + images.length) % images.length)} className="absolute left-4 top-1/2 -translate-y-1/2 bg-black/30 p-2 rounded-full text-white"><ChevronLeft /></button>
            <button onClick={() => setImgIdx((prev) => (prev + 1) % images.length)} className="absolute right-4 top-1/2 -translate-y-1/2 bg-black/30 p-2 rounded-full text-white"><ChevronRight /></button>
            <div className="absolute bottom-4 right-4 bg-black/60 text-white px-3 py-1 rounded-full text-sm">{imgIdx + 1} / {images.length}</div>
          </>
        )}
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        <div className="lg:col-span-2">
          <div className="flex items-center gap-2 mb-2">
            <h1 className="text-3xl font-bold text-main">{property.title}</h1>
            {property.featured && <Star size={24} className="text-yellow-500 fill-yellow-500"/>}
          </div>
          <div className="flex items-center text-muted mt-2"><MapPin size={18} className="mr-1" /> {property.location}</div>
          <div className="flex gap-6 border-y border-ocean-100 py-6 my-6">
             <div className="text-center"><Bed className="mx-auto text-ocean-500"/> <b>{property.bedrooms}</b></div>
             <div className="text-center"><Bath className="mx-auto text-ocean-500"/> <b>{property.bathrooms}</b></div>
             <div className="text-center"><Expand className="mx-auto text-ocean-500"/> <b>{property.area} m²</b></div>
          </div>
          <p className="whitespace-pre-line text-muted mb-8">{property.description}</p>
          <div className="flex flex-wrap gap-2 mb-8">
            {property.features?.map((f, i) => <span key={i} className="bg-ocean-50 text-ocean-700 px-3 py-1 rounded-full text-sm flex items-center"><CheckCircle size={14} className="mr-1"/>{f}</span>)}
          </div>
        </div>
        <div className="lg:col-span-1">
          <div className="bg-card border border-ocean-200 rounded-2xl p-6 shadow-lg sticky top-24">
             <div className="mb-6 text-3xl font-bold text-ocean-600">
                {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(property.price)}
                {property.type === 'rent_seasonal' && <span className="text-sm text-muted font-normal"> /dia</span>}
             </div>
             {property.type === 'rent_seasonal' && (
               <div className="mb-6 space-y-4">
                 <input type="date" className="w-full p-2 border rounded" value={start} onChange={e => setStart(e.target.value)} />
                 <input type="date" className="w-full p-2 border rounded" value={end} onChange={e => setEnd(e.target.value)} />
                 {start && end && <div className="bg-ocean-50 p-3 rounded font-bold text-center">Total: {new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(calcTotal())}</div>}
               </div>
             )}
             <button onClick={handleBook} className="w-full bg-green-600 hover:bg-green-700 text-white font-bold py-3 rounded-xl flex items-center justify-center gap-2"><Phone size={20} /> Contatar</button>
          </div>
        </div>
      </div>
    </div>
  );
};

const AdminForm: React.FC<{ property?: Property | null; onSave: (p: Partial<Property>) => Promise<void>; onCancel: () => void; }> = ({ property, onSave, onCancel }) => {
  const [formData, setFormData] = useState<Partial<Property>>(property || { 
    type: 'sale', 
    features: [], 
    images: [],
    active: true,
    featured: false,
    owner_notes: ''
  });
  const [loading, setLoading] = useState(false);
  const [imgUrl, setImgUrl] = useState('');

  const handleGenerateDesc = async () => {
    setLoading(true);
    const desc = await generatePropertyDescription(formData.features || [], formData.location || '', formData.type || 'sale', formData.bedrooms || 2);
    setFormData(prev => ({ ...prev, description: desc }));
    setLoading(false);
  };

  const addImage = () => { if (imgUrl) { setFormData(prev => ({ ...prev, images: [...(prev.images || []), imgUrl] })); setImgUrl(''); }};
  const removeImage = (idx: number) => setFormData(prev => ({ ...prev, images: prev.images?.filter((_, i) => i !== idx) }));
  const handleFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
       const base64 = await fileToBase64(e.target.files[0]);
       setFormData(prev => ({ ...prev, images: [...(prev.images || []), base64] }));
    }
  };

  return (
    <div className="container mx-auto p-4 max-w-3xl">
      <div className="flex items-center mb-6 text-ocean-600 cursor-pointer" onClick={onCancel}><ArrowLeft className="mr-2" /> Voltar</div>
      <h2 className="text-2xl font-bold mb-6">{property ? 'Editar Imóvel' : 'Novo Imóvel'}</h2>
      <div className="bg-white p-6 rounded-xl shadow-sm border border-ocean-100 space-y-4">
        
        {/* Status e Destaque */}
        <div className="flex gap-4 p-4 bg-gray-50 rounded-lg border border-gray-200">
           <label className="flex items-center gap-2 cursor-pointer">
              <input type="checkbox" checked={formData.active !== false} onChange={e => setFormData({ ...formData, active: e.target.checked })} className="w-5 h-5 accent-ocean-600"/>
              <span className="font-bold flex items-center gap-1">{formData.active !== false ? <Eye size={16}/> : <EyeOff size={16}/>} Visível no Site</span>
           </label>
           <div className="w-px bg-gray-300"></div>
           <label className="flex items-center gap-2 cursor-pointer text-yellow-600">
              <input type="checkbox" checked={formData.featured || false} onChange={e => setFormData({ ...formData, featured: e.target.checked })} className="w-5 h-5 accent-yellow-500"/>
              <span className="font-bold flex items-center gap-1"><Star size={16}/> Destaque / Super Oferta</span>
           </label>
        </div>

        <div className="grid grid-cols-2 gap-4">
          <select className="p-2 border rounded" value={formData.type} onChange={e => setFormData({ ...formData, type: e.target.value as any })}>
            <option value="sale">Venda</option>
            <option value="rent_seasonal">Aluguel Temporada</option>
          </select>
          <input placeholder="Título do Anúncio" className="p-2 border rounded" value={formData.title || ''} onChange={e => setFormData({ ...formData, title: e.target.value })} />
        </div>
        <div className="grid grid-cols-2 gap-4">
          <input placeholder="Localização (Bairro)" className="p-2 border rounded" value={formData.location || ''} onChange={e => setFormData({ ...formData, location: e.target.value })} />
          <input type="number" placeholder="Preço (R$)" className="p-2 border rounded" value={formData.price || ''} onChange={e => setFormData({ ...formData, price: Number(e.target.value) })} />
        </div>
        <div className="grid grid-cols-3 gap-4">
           <input type="number" placeholder="Quartos" className="p-2 border rounded" value={formData.bedrooms || ''} onChange={e => setFormData({ ...formData, bedrooms: Number(e.target.value) })} />
           <input type="number" placeholder="Banheiros" className="p-2 border rounded" value={formData.bathrooms || ''} onChange={e => setFormData({ ...formData, bathrooms: Number(e.target.value) })} />
           <input type="number" placeholder="Área (m²)" className="p-2 border rounded" value={formData.area || ''} onChange={e => setFormData({ ...formData, area: Number(e.target.value) })} />
        </div>

        {/* Campo Interno */}
        <div>
           <label className="block text-sm font-medium text-muted mb-1 flex items-center gap-1"><FileText size={14}/> Anotações Internas (Proprietário, Chaves, etc)</label>
           <input className="w-full p-2 border border-yellow-200 bg-yellow-50 rounded text-sm" placeholder="Ex: Chave na portaria, Proprietário Sr. João (12) 999..." value={formData.owner_notes || ''} onChange={e => setFormData({ ...formData, owner_notes: e.target.value })} />
        </div>

        <div>
          <label className="block text-sm font-medium text-muted mb-1">Fotos do Imóvel</label>
          <div className="flex gap-2 mb-2">
            <input type="text" placeholder="URL da imagem" className="flex-1 p-2 border rounded" value={imgUrl} onChange={e => setImgUrl(e.target.value)} />
            <button onClick={addImage} className="bg-ocean-100 text-ocean-600 px-4 rounded"><Plus /></button>
            <label className="bg-ocean-600 text-white px-4 py-2 rounded cursor-pointer flex items-center"><Camera size={20}/><input type="file" hidden onChange={handleFile} accept="image/*"/></label>
          </div>
          <div className="flex gap-2 overflow-x-auto py-2">
            {formData.images?.map((img, i) => (
              <div key={i} className="relative w-20 h-20 flex-shrink-0">
                <img src={img} className="w-full h-full object-cover rounded" />
                <button onClick={() => removeImage(i)} className="absolute -top-1 -right-1 bg-red-500 text-white rounded-full p-0.5"><X size={12}/></button>
              </div>
            ))}
          </div>
        </div>
        <textarea placeholder="Descrição" rows={5} className="w-full p-2 border rounded" value={formData.description || ''} onChange={e => setFormData({ ...formData, description: e.target.value })} />
        <div className="flex gap-2 justify-end">
          <button onClick={handleGenerateDesc} disabled={loading} className="flex items-center gap-2 text-ocean-600 bg-ocean-50 px-4 py-2 rounded hover:bg-ocean-100">
             <Sparkles size={16} /> {loading ? 'Gerando...' : 'Gerar Descrição com IA'}
          </button>
          <button onClick={() => onSave(formData)} className="bg-ocean-600 text-white px-6 py-2 rounded hover:bg-ocean-700">Salvar Imóvel</button>
        </div>
      </div>
    </div>
  );
};

const AdminSettings: React.FC<{ settings: SiteSettings; onSave: (s: SiteSettings) => void }> = ({ settings, onSave }) => {
  const [local, setLocal] = useState(settings);
  const handleFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files?.[0]) {
       const base64 = await fileToBase64(e.target.files[0]);
       setLocal({ ...local, logoUrl: base64 });
    }
  };
  return (
    <div className="container mx-auto p-4 max-w-4xl">
      <h2 className="text-2xl font-bold mb-6 flex items-center gap-2"><Settings/> Configurações do Site</h2>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        <div className="space-y-4">
           <div className="bg-white p-6 rounded-xl shadow-sm border border-ocean-100">
              <h3 className="font-bold mb-4 flex items-center gap-2"><Palette size={18}/> Aparência</h3>
              <label className="block text-sm mb-1">Nome do Site</label>
              <input className="w-full p-2 border rounded mb-3" value={local.siteName} onChange={e => setLocal({ ...local, siteName: e.target.value })} />
              <label className="block text-sm mb-1">Logo (URL ou Upload)</label>
              <div className="flex gap-2 mb-3">
                <input className="flex-1 p-2 border rounded" value={local.logoUrl || ''} onChange={e => setLocal({ ...local, logoUrl: e.target.value })} placeholder="/img/logo.png" />
                <label className="bg-gray-200 px-3 py-2 rounded cursor-pointer"><Upload size={20}/><input type="file" hidden onChange={handleFile}/></label>
              </div>
              <label className="block text-sm mb-1">Tema de Cores</label>
              <div className="grid grid-cols-4 gap-2">
                {['ocean', 'nature', 'sunset', 'dark'].map((c) => (
                  <button key={c} onClick={() => setLocal({ ...local, primaryColor: c as any })}
                    className={`h-8 rounded-full border-2 ${local.primaryColor === c ? 'border-black' : 'border-transparent'}`}
                    style={{ background: c === 'ocean' ? '#0ea5e9' : c === 'nature' ? '#22c55e' : c === 'sunset' ? '#ef4444' : '#333' }}
                  />
                ))}
              </div>
           </div>
        </div>
        <div className="space-y-4">
           <div className="bg-white p-6 rounded-xl shadow-sm border border-ocean-100">
              <h3 className="font-bold mb-4 flex items-center gap-2"><Phone size={18}/> Contato</h3>
              <input className="w-full p-2 border rounded mb-3" placeholder="Endereço" value={local.contact.address} onChange={e => setLocal({ ...local, contact: { ...local.contact, address: e.target.value } })} />
              <input className="w-full p-2 border rounded mb-3" placeholder="Telefone Principal" value={local.contact.phone} onChange={e => setLocal({ ...local, contact: { ...local.contact, phone: maskPhone(e.target.value) } })} />
              <input className="w-full p-2 border rounded mb-3" placeholder="WhatsApp Reservas" value={local.contact.bookingPhone || ''} onChange={e => setLocal({ ...local, contact: { ...local.contact, bookingPhone: maskPhone(e.target.value) } })} />
              <input className="w-full p-2 border rounded mb-3" placeholder="Email" value={local.contact.email} onChange={e => setLocal({ ...local, contact: { ...local.contact, email: e.target.value } })} />
              <input className="w-full p-2 border rounded mb-3" placeholder="Instagram" value={local.social.instagram} onChange={e => setLocal({ ...local, social: { ...local.social, instagram: e.target.value } })} />
           </div>
        </div>
      </div>
      <button onClick={() => onSave(local)} className="mt-6 w-full bg-ocean-600 text-white py-3 rounded-xl font-bold hover:bg-ocean-700 flex justify-center gap-2"><Save/> Salvar Configurações</button>
    </div>
  );
};

const AppContent: React.FC = () => {
  const [properties, setProperties] = useState<Property[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [settings, setSettings] = useState<SiteSettings>(INITIAL_SETTINGS);
  const [view, setView] = useState<ViewState>(ViewState.HOME);
  const [selectedProperty, setSelectedProperty] = useState<Property | null>(null);
  const [dbError, setDbError] = useState<string | null>(null);
  const [logoFailed, setLogoFailed] = useState(false);
  const [showDbSetup, setShowDbSetup] = useState(false);
  const loadingTimeoutRef = useRef<any>(null);

  // --- FORÇAR REMOÇÃO DO LOADER ---
  useLayoutEffect(() => {
    const loader = document.getElementById('loading-screen');
    if (loader) loader.style.display = 'none';
  }, []);

  useEffect(() => {
    console.log("App V.3.4 - Audit & Update");
    fetchSettings();
    fetchProperties();
    return () => { if (loadingTimeoutRef.current) clearTimeout(loadingTimeoutRef.current); };
  }, []);

  useEffect(() => {
    document.body.className = `bg-page text-main transition-colors duration-300 theme-${settings.primaryColor}`;
  }, [settings]);

  const fetchSettings = async () => {
    try {
      const { data, error } = await supabase.from('site_settings').select('data').single();
      if (error) {
        if (error.code === '42P01') {
          console.warn("Tabela site_settings não existe.");
          setShowDbSetup(true);
        }
      } else if (data && data.data && Object.keys(data.data).length > 0) {
        setSettings({ ...INITIAL_SETTINGS, ...data.data });
      }
    } catch (e) { 
      console.log("Usando configurações padrão (Local)", e); 
    }
  };

  const fetchProperties = async () => {
    setIsLoading(true);
    setDbError(null);
    if (loadingTimeoutRef.current) clearTimeout(loadingTimeoutRef.current);
    loadingTimeoutRef.current = setTimeout(() => {
      if (isLoading) {
        setIsLoading(false);
        setDbError("O banco de dados demorou muito para responder. Verifique sua conexão.");
      }
    }, 8000);

    try {
      // Ordena: Primeiro Destaques, depois data de criação
      const { data, error } = await supabase.from('properties')
        .select('*')
        .order('featured', { ascending: false, nullsLast: true })
        .order('created_at', { ascending: false });

      if (loadingTimeoutRef.current) clearTimeout(loadingTimeoutRef.current);

      if (error) {
        if (error.code === '42P01' || error.message.includes('does not exist')) setShowDbSetup(true);
        else setDbError(error.message || JSON.stringify(error));
      } else if (data) {
        setProperties(data.map((p: any) => ({ 
          ...p, 
          images: p.images || [], 
          features: p.features || [],
          // Garante valores padrão se a coluna for nova
          active: p.active !== false,
          featured: p.featured === true
        })));
      }
    } catch (err: any) {
      setDbError(err.message || "Erro de conexão.");
    }
    setIsLoading(false);
  };

  const handleSaveSettings = async (newSettings: SiteSettings) => {
    setSettings(newSettings);
    const { error } = await supabase.from('site_settings').upsert({ id: 1, data: newSettings });
    if (error) {
       if (error.code === '42P01') setShowDbSetup(true);
       else alert("Erro ao salvar no banco: " + error.message);
    } else {
       alert("Configurações salvas no Banco de Dados!");
    }
  };

  const handleSaveProperty = async (p: Partial<Property>) => {
    const { error } = p.id 
      ? await supabase.from('properties').update(p).eq('id', p.id)
      : await supabase.from('properties').insert(p);
    
    if (error) alert("Erro: " + error.message);
    else {
      fetchProperties();
      setView(ViewState.ADMIN_PROPERTIES);
    }
  };

  const handleDelete = async (id: string) => {
    if (confirm("Tem certeza que deseja excluir?")) {
      await supabase.from('properties').delete().eq('id', id);
      fetchProperties();
    }
  };

  const handleSeed = async () => {
    const SAMPLE_PROPERTIES = [
      {
        title: "Casa de Alto Padrão em Itamambuca",
        description: "Espetacular casa pé na areia com piscina.",
        location: "Itamambuca, Ubatuba",
        price: 3500,
        type: "rent_seasonal",
        bedrooms: 5,
        bathrooms: 6,
        area: 450,
        features: ["Piscina", "Churrasqueira", "Wi-Fi"],
        images: ["https://images.unsplash.com/photo-1600596542815-60c37c6525fa?auto=format&fit=crop&w=800"],
        views: 120,
        featured: true,
        active: true
      }
    ];

    setIsLoading(true);
    const { error } = await supabase.from('properties').insert(SAMPLE_PROPERTIES);
    if (error) {
      alert("Erro ao criar dados: " + error.message);
      if (error.code === '42P01') setShowDbSetup(true);
    } else {
      alert("Dados de teste criados!");
      fetchProperties();
    }
    setIsLoading(false);
  };

  // Filtragem para o usuário comum (só mostra ativos)
  const visibleProperties = properties.filter(p => view === ViewState.ADMIN_PROPERTIES ? true : p.active !== false);

  if (showDbSetup) return <DatabaseSetup />;

  return (
    <div className="min-h-screen bg-page font-sans text-main">
      <header className="bg-card shadow-sm sticky top-0 z-50 border-b border-ocean-100 h-16 flex items-center justify-between px-4">
         <div className="flex items-center gap-3 font-bold text-xl cursor-pointer" onClick={() => setView(ViewState.HOME)}>
            {settings.logoUrl && !logoFailed ? (
               <img src={settings.logoUrl} className="h-12 w-auto" onError={() => setLogoFailed(true)} />
            ) : <UbatubaLogo className="h-12 w-12" />}
            <span className="hidden md:block text-ocean-800">{settings.siteName}</span>
         </div>
         <div className="flex gap-2">
           {view === ViewState.HOME ? (
             <button onClick={() => setView(ViewState.ADMIN_PROPERTIES)} className="px-4 py-2 border rounded-full hover:bg-ocean-50 text-ocean-700 flex gap-2 text-sm font-medium">
                <UserCircle size={18}/> Área Admin
             </button>
           ) : (
             <button onClick={() => setView(ViewState.HOME)} className="px-4 py-2 border rounded-full hover:bg-ocean-50 text-ocean-700 flex gap-2 text-sm font-medium">
                <Globe size={18}/> Ver Site
             </button>
           )}
         </div>
      </header>

      <main>
        {dbError && (
          <div className="container mx-auto p-4 mt-4">
             <div className="bg-red-100 text-red-800 p-4 rounded border border-red-200 flex justify-between items-center">
                <span><strong>Erro:</strong> {dbError}</span>
                <button onClick={fetchProperties} className="bg-red-200 px-3 py-1 rounded hover:bg-red-300 text-sm font-bold">Tentar Novamente</button>
             </div>
          </div>
        )}

        {view === ViewState.HOME && (
          <div className="container mx-auto px-4 py-8 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {visibleProperties.map(p => (
              <div key={p.id} className="relative group">
                 {p.featured && <div className="absolute -top-3 left-4 z-10 bg-yellow-500 text-white px-3 py-1 rounded-full text-xs font-bold shadow flex items-center gap-1"><Star size={12}/> DESTAQUE</div>}
                 <PropertyCard property={p} onClick={() => { setSelectedProperty(p); setView(ViewState.DETAILS); }} />
              </div>
            ))}
            {visibleProperties.length === 0 && !isLoading && !dbError && (
               <div className="col-span-full text-center py-12 text-muted">
                  <p>Nenhum imóvel disponível no momento.</p>
                  <button onClick={() => setView(ViewState.ADMIN_PROPERTIES)} className="mt-4 text-ocean-600 font-bold">Acessar Painel Admin</button>
               </div>
            )}
          </div>
        )}
        
        {view === ViewState.DETAILS && selectedProperty && <PropertyDetails property={selectedProperty} onBack={() => setView(ViewState.HOME)} bookingPhone={settings.contact.bookingPhone || settings.contact.phone} />}
        
        {view === ViewState.ADMIN_PROPERTIES && (
           <div className="container mx-auto p-4 flex flex-col md:flex-row gap-6">
              <div className="w-full md:w-64 flex flex-row md:flex-col gap-2 overflow-x-auto pb-2 md:pb-0 sticky top-20 h-fit z-10 bg-page">
                  <button className="flex-1 bg-ocean-600 text-white p-3 rounded text-left font-bold flex gap-2"><LayoutDashboard size={18}/> Imóveis</button>
                  <button onClick={() => setView(ViewState.ADMIN_SETTINGS)} className="flex-1 bg-white text-muted p-3 rounded text-left hover:bg-gray-50 flex gap-2"><Settings size={18}/> Configurações</button>
                  <button onClick={handleSeed} className="flex-1 bg-purple-100 text-purple-700 p-3 rounded text-left hover:bg-purple-200 flex gap-2"><Database size={18}/> Gerar Teste</button>
              </div>
              
              <div className="flex-1">
                <div className="flex justify-between items-center mb-6">
                   <h1 className="text-2xl font-bold text-ocean-800">Meus Imóveis</h1>
                   <button onClick={() => { setSelectedProperty(null); setView(ViewState.ADMIN_FORM); }} className="bg-ocean-600 text-white px-4 py-2 rounded-full hover:bg-ocean-700 flex items-center gap-2 font-bold shadow-lg"><Plus size={20}/> Novo Imóvel</button>
                </div>
                <div className="grid grid-cols-1 gap-4">
                   {properties.map(p => (
                     <div key={p.id} className={`bg-white p-4 rounded-lg shadow flex justify-between items-center ${p.active === false ? 'opacity-60 bg-gray-50' : ''} ${p.featured ? 'border-l-4 border-yellow-400' : ''}`}>
                        <div className="flex items-center gap-4">
                           <img src={p.images[0] || 'https://via.placeholder.com/50'} className="w-16 h-16 object-cover rounded" />
                           <div>
                              <div className="flex items-center gap-2">
                                <h3 className="font-bold">{p.title}</h3>
                                {p.active === false && <span className="text-xs bg-gray-200 text-gray-600 px-2 rounded">Inativo</span>}
                                {p.featured && <Star size={14} className="text-yellow-500 fill-yellow-500"/>}
                              </div>
                              <p className="text-sm text-muted">{p.location}</p>
                           </div>
                        </div>
                        <div className="flex gap-2">
                           <button onClick={() => { setSelectedProperty(p); setView(ViewState.ADMIN_FORM); }} className="p-2 text-blue-600 hover:bg-blue-50 rounded"><Edit size={18}/></button>
                           <button onClick={() => handleDelete(p.id)} className="p-2 text-red-600 hover:bg-red-50 rounded"><Trash2 size={18}/></button>
                        </div>
                     </div>
                   ))}
                   {properties.length === 0 && <div className="text-center text-muted py-8">Nenhum imóvel cadastrado.</div>}
                </div>
              </div>
           </div>
        )}

        {view === ViewState.ADMIN_FORM && (
          <AdminForm 
            property={selectedProperty} 
            onSave={handleSaveProperty} 
            onCancel={() => setView(ViewState.ADMIN_PROPERTIES)} 
          />
        )}

        {view === ViewState.ADMIN_SETTINGS && (
          <div className="container mx-auto p-4">
             <button onClick={() => setView(ViewState.ADMIN_PROPERTIES)} className="mb-4 flex items-center text-muted hover:text-ocean-600"><ArrowLeft size={18} className="mr-2"/> Voltar para Imóveis</button>
             <AdminSettings settings={settings} onSave={handleSaveSettings} />
          </div>
        )}

      </main>
    </div>
  );
};

const App: React.FC = () => <ErrorBoundary><AppContent /></ErrorBoundary>;
export default App;